// import "@fortawesome/fontawesome-free/js/all";
import "../admin/vendor/bootstrap/css/bootstrap.min"
import "../admin/vendor/metisMenu/metisMenu"
import "../admin/dist/css/sb-admin-2"
// import "../admin/vendor/morrisjs/morris"
import "../admin/vendor/font-awesome/css/font-awesome.min"

import "../admin/vendor/jquery/jquery.min"
import "../admin/vendor/bootstrap/js/bootstrap.min"
import "../admin/vendor/metisMenu/metisMenu.min"
// import "../admin/vendor/raphael/raphael"
// import "../admin/vendor/raphael/raphael.min"
// import "../admin/vendor/morrisjs/morris.min"
// import "../admin/data/morris-data"
import "../admin/dist/js/sb-admin-2"